spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/security/**
          filters:
            - AuthenticationFilter
        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/user/management/**
